services:
  api:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
      - run-php:/var/run/php
    depends_on:
      - postgres
      - redis
    environment:
      APP_DEBUG: "true"
      DB_HOST: postgres
      LOG_CHANNEL: stderr
      DB_CONNECTION: pgsql
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PORT: ${DB_PORT}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - 8000:8000
    command: "php artisan serve"

  symbolrefresh:
      build:
          context: ./
          dockerfile: docker/php/Dockerfile
      volumes:
          - ./:/app
          - run-php:/var/run/php
      depends_on:
	  - api
          - postgres
          - redis
      environment:
          APP_DEBUG: "true"
          DB_HOST: postgres
          LOG_CHANNEL: stderr
          DB_CONNECTION: pgsql
          DB_PASSWORD: ${DB_PASSWORD}
          DB_DATABASE: ${DB_DATABASE}
          DB_USERNAME: ${DB_USERNAME}
          DB_PORT: ${DB_PORT}
          REDIS_HOST: redis
          REDIS_PORT: ${REDIS_PORT}
      entrypoint: /bin/sh -c "sleep 60 && php artisan symbol:refresh"
      restart: "unless-stopped"

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"

volumes:
  run-php:
  postgres_data:

